---
default:
  image: registry.cri.epita.fr/cri/infrastructure/nixpie/nixos-pie
  before_script:
    - mkdir -p /tmp /var/tmp
    - meson setup -Ddoc=true -Dtestunit=true builddir

stages:
  - build
  - test
  - qa
  - doc

build:
  stage: build
  script:
    #- meson compile -C builddir
    - ninja -C builddir
  artifacts:
    paths:
      - builddir/42sh
      - builddir/testsuite
    expose_as: 42sh

tests_42sh:
  stage: test
  dependencies:
    - build
  script:
    - tests/run_tests builddir/42sh

tests_dash:
  stage: test
  script:
    - tests/run_tests dash

unit_test:
  stage: test
  dependencies:
    - build
  script:
    - builddir/testsuite

clang-format:
  stage: qa
  needs: []
  before_script: []
  script:
    - find . -type f -name '*.[ch]' -exec clang-format --style=file -i {} ';'
    - git diff --exit-code
  after_script:
    - git diff > diff
  artifacts:
    paths:
      - diff
    expose_as: clang-format diff
    when: on_failure

coding-style:
  image: pierre42100/debian-wget-clang-format
  stage: qa
  needs: []
  before_script: []
  script:
    - tests/check_coding_style

doc:
  stage: doc
  needs: []
  script:
    - meson compile -C builddir doxygen_doc
  artifacts:
    paths:
      - builddir/doxygen_doc
    expose_as: documentation
